# Generated by Django 3.2 on 2021-04-10 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210410_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='network.userroles'),
        ),
    ]
